### PR TITLE
fix flow typing | remove `createSender` API

### LINKED ISSUE #6: Improve Flow Coverage
Current state of Flow coverage doesn't allow to use `action.payload` in the reducer:

```js
static reducer(action, state) {
    switch (action.type) {
      case "CLICK":
        return Update({ count: action.payload });  // Error here
      case "CLACK":
        return NoUpdate();
      default: {
        absurd(action.type);
        return NoUpdate();
      }
    }
  }
```

Flow error:

```
Cannot get action.payload because property payload is missing in object type [1].

     type-definitions/__tests__/ReComponent.js
     152│   static reducer(action, state) {
     153│     switch (action.type) {
     154│       case "CLICK":
     155│         return Update({ count: action.payload });
     156│       case "CLACK":
     157│         return NoUpdate();
     158│       default: {

     type-definitions/ReComponent.js.flow
 [1]  31│     action: { type: ActionType },

```

I believe that fixing this is very important for everyone using `flow` in their project

### PR DESCRIPTION
**Pull request by wzrdzl**
Fixes #6

- Requires `Action` instead of `ActionType` as a generic parameter of `ReComponent` and `RePureComponent`
- makes sure the type of the `action.payload` is preserved throughout the component's API and reducer

Unfortunately, in order to ensure proper type-checking I had to remove `createSender` API.
I simply didn't manage to come up with typing that would ensure the correct `payload` typing, while maintaining the same API of `createSender`. Please let me know if you see a solution for it.

Even though it has to be removed, I don't think it would make the ergonomics of `ReComponent` significantly worse:
```js
this.handleClick = this.createSender("CLICK");
```
becomes
```js
this.handleClick = () => this.send({ type: "CLICK" });
```
or
```js
this.handleClick = (clicks: number) => this.send({ type: "CLICK", payload: clicks });
```

NOTE: I did not fix documentation (remove all mentions of `createSender` and fix the examples) yet. I would like to wait for the code review first just to know if you are OK with this breaking change. If you decide to proceed with these changes I will make sure the docs are updated as well

### CODE REVIEW

**Comment by wzrdzl** [comment]
Hi @philipp-spiess ,

Thanks for such a quick reaction!

I agree that `createSender` is very convenient API and can definitely be useful, especially for someone who doesn't use flow. 

What I would do though, is to update the documentation so that it's clear that you are losing the typing of `payload` if you use `createSender` API (`payload` is effectively typed as `any`). What do you think, shall I update it?

> In addition to that, we'd probably want to publish this as a major release as this breaks existing types but I see no issue in that.
I agree, for any flow project these changes are breaking

**Comment by philipp-spiess** [comment]
It would be great if you could update the docs. I think we should remove `createSender` from the Flow examples and add a note as you said.

We should also roll back the tests I suppose so that we also test `createSender`.

Thank you for your help!

**Comment by wzrdzl** [comment]
Sure, no worries will update everything! :)

**Comment by wzrdzl** [comment]
@philipp-spiess I updated docs and brought back some `this.createSender` usages in the tests

**Comment by wzrdzl** [comment]
Thanks man, it's been a pleasure to collaborate with you :)

**Comment by philipp-spiess** [comment]
The pleasure is all mine 😊 

FYI I've released `1.0.0-rc.1` with the `next` tag now. Be sure to check it out!

https://github.com/philipp-spiess/react-recomponent/releases/tag/v1.0.0-rc.1

**Pull request merged**
